apiVersion: v1
kind: Pod
metadata:
  name: flipkartvolume
spec:
  containers:
    - name: c00
      image: centos
      command: ["/bin/bash","-c","sleep 15000"]
      volumeMounts:
        - name: liki
          mountPath: "/tmp/signup"
    - name: c01
      image: centos
      command: ["/bin/bash","-c","sleep 10000"]
      volumeMounts:
        - name: liki
          mountPath: "/tmp/login"
  volumes:
    - name: liki
      emptyDir: {}
