apiVersion: v1
kind: Pod
metadata:
  name: flipkart
  labels:
    team: likitha
    department: devops
spec:
  containers:
    - name: signup
      image: nginx
      ports:
        - containerPort: 80
