apiVersion: v1
kind: ReplicationController
metadata:
  name: cluster
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: liki
      labels:
        app: nginx
    spec:
      containers:
        - name: signup
          image: nginx
          ports:
            - containerPort: 80
